# CloudGreen OS — Neo4j Community Edition Secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: data-system
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: cloudgreen-os
    app.kubernetes.io/component: graph-database
type: Opaque
data:
  # neo4j
  NEO4J_USERNAME: bmVvNGo=
  # cg-graph-s3cur3-2026!
  NEO4J_AUTH: bmVvNGovY2ctZ3JhcGgtczNjdXIzLTIwMjYh
